version: '3.3'
services:
  mysql:
    image: mysql:8.0.22
    platform: linux/x86_64
    container_name: MindtechApps
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MindtechApps